server:
  port: 8000

spring:
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springmvc2?serverTimezone=UTC

    username: root
    password: root

